### ISSUE TITLE
Where are the pre-compiled .deb files?

### ISSUE THREAD

**Issue by farmwald** [WireGuard/wireguard-vyatta-ubnt#1]
I must be missing something. Under each release, I see source code, but no .deb files?
Where should I be looking?

**Comment by FossoresLP** [comment]
There has not been a release, yet. The listed releases are simply the git tags. A new release will be posted by tomorrow.
I will keep this open until then in case someone else has the same question.

**Comment by bneijt** [comment]
Don't forget, when doing a release, to mention how and if it works with firmware 2.x firmware and/or 1.x firmware as mentioned on https://github.com/Lochnair/vyatta-wireguard/releases/tag/0.0.20191219-2

**Comment by FossoresLP** [comment]
The new release is out now, closing this issue.
@bneijt Your concern should be addressed but feel free to open a new issue if you think it should still be made more obvious.
