### ISSUE TITLE
What is the procedure to use the new UDM/UDM Pro version

### ISSUE THREAD

**Issue by tuxtof** [WireGuard/wireguard-vyatta-ubnt#102]
i just see udm package in the last release
but no documentation , what is the install logic

**Comment by tusc** [comment]
Hi tuxtof, you can follow this documentation in the interim as it's being updated on this site: https://github.com/tusc/wireguard-kmod

**Comment by tuxtof** [comment]
Thanks @tusc 
what is the difference between the two kernel modules ?

**Comment by peacey** [comment]
@tuxtof, there is no difference. We are just in the process of migrating from the old repo to this repo and haven't finished migrating the documentation yet.

**Comment by tuxtof** [comment]
perfect thanks for the quick response
