### ISSUE TITLE
Add description field to peer

### ISSUE THREAD

**Issue by joltcan** [WireGuard/wireguard-vyatta-ubnt#104]
Thanks for you great work!

Would it be possible to add a description field to the peers? Would be nice to just add comment field like on the firewall rules:

```
gw# show interfaces wireguard wg0 peer foobar= {
    allowed-ips 10.0.0.12/32
    description "client example.com"
}

**Comment by poisonsnak** [comment]
I think this exists already. At least it does for me on an ER-X running 2.0.9-hotfix.2, module 1.0.20210606, tools 1.0.20210424 :

```
user@router# show interfaces wireguard wg0 peer foobar=
 allowed-ips 10.0.0.12/32
 description MyDescription
[edit]
```
![Untitled](https://user-images.githubusercontent.com/18585880/135679134-2e6ed3d8-0954-406e-ac67-285e9e6bfb5d.png)

**Comment by joltcan** [comment]
Thought I didnt see it in my ER lite, but Ill double check!

**Comment by joltcan** [comment]
Oh, nevermind me.
