### ISSUE TITLE
IPv6 MSS range

### ISSUE THREAD

**Issue by SwimGeek** [WireGuard/wireguard-vyatta-ubnt#110]
### Package version

1.0.20210606-2

### Firmware version

v2.0.9-hotfix.2

### Device

EdgeRouter X (SFP) - e50

### Issue description

Wireguard allows you to set the MTU to 1280. For IPv6 traffic, I think that would bring the MSS value to 1280-60 = 1220, but that seems to be outside the range allowed by the configuration system.

command: set firewall options mss-clamp6 mss 1220
response: MSS must be between 1280 and 1492

I suspect it should allow mss-clamp6 value to be as low as 1220.

**Comment by vchrizz** [comment]
I'm not sure if the WireGuard package is directly related to this issue, as it looks like an EdgeOS issue.
So I guess this issue should be reported to the [Ubiquiti forum](https://community.ui.com/questions/create).

**Comment by BrianG61UK** [comment]
IME you are unlikely to need MSS clamping for IPv6. IPv6 normally does path MTU discovery correctly and will work better without MSS clamping. Remove the mss-clamp6 section from your configuration.
`delete firewall options mss-clamp6`

**Comment by FossoresLP** [comment]
Closing as not planned since there is nothing we can do to change the limits for mss-clamp6.
vchrizz correctly pointed out the Ubiquiti forums as the correct place to discuss this issue.
