### ISSUE TITLE
Persistent on reboot for UXG-Pro

### ISSUE THREAD

**Issue by matellis** [WireGuard/wireguard-vyatta-ubnt#118]
The documentation describes how to install WireGuard on many devices including the UXG-Pro, but it does not show how to make it start consistently when the device is rebooted. There are instructions for the UDM-Pro but they don't appear to work on the UXG, besides I'm a bit wary of experimenting on my production UXGs with my current level of ignorance.

Short version: please support reboot persistence for UXG-Pro.

**Comment by peacey** [comment]
Hi @matellis,

Unfortunately there is no way to run things on boot on the UXG-Pro, as far as I know. The UXG-Pro does not have the required systemd nor unifi-os container to do the boot trick as was done with the UDM-Pro or newer UDR/UDM-SE. 

Perhaps in the future if Ubiquiti updates the firmware of the UXG-Pro to the 2.x branch like the UDM-SE, it might be possible to implement boot scripts with systemd. However, at this time it is not possible. 

This is not something we can implement unfortunately as it would require flashing a completely new firmware. 

If you are aware of any way to run boot scripts on the UXG-Pro, feel free to share and we will definitely add the instructions.

**Comment by matellis** [comment]
Thank you for confirming what I thought. We'll just have to keep bugging Ubiquiti.
