### ISSUE TITLE
Confusing and faulty wiki text

### ISSUE THREAD

**Issue by hb0nes** [WireGuard/wireguard-vyatta-ubnt#125]
### Package version

1

### Firmware version

1

### Device

UniFi Security Gateway Pro 4 - UGW4

### Issue description

In the wiki, after curling and installing, there is this entry:
```
After you will have be able to create a wireguard interface (show interfaces).
```

What?
Am I supposed to have an interface now? 
Or do I have to create one? If so, how does `show interfaces` help me in creating one?

I suggest someone rewrite this, as it's not adding anything in its current form.

**Comment by FossoresLP** [comment]
Hi @hb0nes,
thank you for reporting this.
The wiki has been updated to explain what to do after installation.
