### ISSUE TITLE
UXG persistence

### ISSUE THREAD

**Issue by trobotham** [WireGuard/wireguard-vyatta-ubnt#127]
It looks like UXG isn't supported in the script for persistance, I am struggling to figure out how to manually setup persistence. It looks like podman exists but unifi-os is a non-existent container.

Any ideas or potential support?

**Comment by peacey** [comment]
Hi @trobotham,

Have you seen the [uxg-boot](https://github.com/unifi-utilities/uxg-boot) project? It seems to implement the on boot support for UXG. I will add it to the README, though I haven't tested it myself.
