### ISSUE TITLE
Build for EdgeRouter 10X (ER-10) device?

### ISSUE THREAD

**Issue by LeoWinterDE** [WireGuard/wireguard-vyatta-ubnt#132]
Which build runs on the EdgeRouter 10X ([ER-10](https://dl.ubnt.com/qsg/ER-10X/ER-10X_EN.html)) device?

```
$ /usr/sbin/ubnt-hal show-version
Version:      v2.0.9-hotfix.4
Build ID:     5521907
Build on:     06/30/22 06:57
Copyright:    2012-2020 Ubiquiti Networks, Inc.
HW model:     EdgeRouter 10X
```

Rel: #105

**Comment by dc361** [comment]
It looks like your ER-10 device takes the same EdgeOS as  the the ER-X, ER-X-SFP and EP-R6 as seen on the UI download site:

EdgeRouter ER-X/ER-X-SFP/EP-R6/ER-10X: Firmware v2.0.9-hotfix.4

I would expect the following version to work:

https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20220627-1/e50-v2-v1.0.20220627-v1.0.20210914.deb

**Comment by LeoWinterDE** [comment]
Thanks its working just fine, docs update in #136
