### ISSUE TITLE
Archive.org mirror of UDR GPL Archives

### ISSUE THREAD

**Issue by whi-tw** [WireGuard/wireguard-vyatta-ubnt#141]
Hullo,

While working on https://github.com/whi-tw/macvlan-unifi-udr, I realised it's possible that the Ubiquiti GPL dumps may go away some time. I have created an item on archive.org to archive them more permanently: https://archive.org/details/unifi-udr-gpl-archives.

I found the original URL to the `tar.gz` file in this repository initially, so wanted to make sure my archive found its way back to you.

It is possible to pull this down directly from Archive.org if you choose, via the [permalinks](https://archive.org/download/unifi-udr-gpl-archives). In my GitHub action, I am caching it, so I don't end up hitting them too hard:

https://github.com/whi-tw/macvlan-unifi-udr/blob/caaef94ed160c82ce0dc935f825638857592863a/.github/workflows/build.yml#L38-L55

Unsure if this is something y'all are interested in, but there it is.

Context: 

https://github.com/WireGuard/wireguard-vyatta-ubnt/blob/e71ad148f2972cabb0941a0c91e00157c4d82f2b/unifios/bases/udr-2.2.12/buildroot-config.txt#L370

**Comment by FossoresLP** [comment]
Hi @whi-tw,
Thank you for letting us know.
I'll probably stick with the original Ubiquiti links for now. One of my main goals with this repository is to make it as easy to maintain as possible and using the original link makes it very clear where to look for new versions.
Having archives is great though and I'll keep them in mind in case anything ever happens to the official links. I might even look into archiving GPL archives across all products.
The issue will be marked as won't fix for now, but I'll keep your archive in mind.

**Comment by whi-tw** [comment]
@FossoresLP Entirely valid!

FYI, I have added a dump from the latest firmware (3.x) and would be interested to know whether it's in the S3 bucket, as I was sent it via a password protected file transfer link. Unsure if this is the same process as before, or even if this S3 bucket is owned by ubiquiti. Food for thought.

**Comment by FossoresLP** [comment]
@whi-tw Thanks for your reply.

After thinking about it a little more, I'm not sure whether the S3 bucket is actually official.

I didn't work on the UnifiOS implementation myself.

@peacey  If I remember correctly, we talked about the location of the GPL archives but I can't find that conversation right now. Could you elaborate on where the S3 bucket comes from?

**Comment by peacey** [comment]
Hi @FossoresLP,

Sorry for the late reply, was on vacation. 

As I've mentioned in our discussion before, the S3 is my personal one and not connected to Ubiquiti. But the sources were obtained from Ubiquiti directly by emailing them. 

@whi-tw, if you give me the 3.0 sources, I would be happy to put them on the S3 bucket. I was planning to ask Ubiquiti for more sources once 2.x and 3.x become official for UDM-Pro.

**Comment by whi-tw** [comment]
@peaceyThey are all in the Archive.org link further up this thread: https://archive.org/details/unifi-udr-gpl-archivesI’ll probably keep using the permalinks from there for my own CI, but more archival is good archival, right?On 7 Jan 2023, at 18:24, peacey ***@***.***> wrote:﻿
Hi @FossoresLP,
Sorry for the late reply, was on vacation.
As I've mentioned in our discussion before, the S3 is my personal one and not connected to Ubiquiti. But the sources were obtained from Ubiquiti directly by emailing them.
@whi-tw, if you give me the 3.0 sources, I would be happy to put them on the S3 bucket. I was planning to ask Ubiquiti for more sources once 2.x and 3.x become official for UDM-Pro.
