### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by darknet1944** [WireGuard/wireguard-vyatta-ubnt#142]

**Comment by darknet1944** [comment]
EdgeRouter X 
Currently running EdgeOSv2.0.9-hotfix.4
Download from repository via curl command.

ubnt@EdgeRouter-X-5-Port:~$ sudo dpkg -i e50-v2-v1.0.20220627-v1.0.20210914.deb  
dpkg-deb: error: 'e50-v2-v1.0.20220627-v1.0.20210914.deb' is not a debian format archive
dpkg: error processing archive e50-v2-v1.0.20220627-v1.0.20210914.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 e50-v2-v1.0.20220627-v1.0.20210914.deb
Please advise.

**Comment by dc361** [comment]
What curl command line did you use to download the package.   I just tried re-installing that version on an ER-X but I scp'd the file that I had previously downloaded from my windows machine.

**Comment by vchrizz** [comment]
I guess you should use `-L` or `--location` option for curl to properly follow the redirect(s) on github.
Like for example:
```
curl -L -o e50-v2-v1.0.20220627-v1.0.20210914.deb https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20220627-1/e50-v2-v1.0.20220627-v1.0.20210914.deb
sudo dpkg -i e50-v2-v1.0.20220627-v1.0.20210914.deb
```

from the manpage of curl:
> -L, --location
> (HTTP)  If  the server reports that the requested page has moved to a different location (indicated with a Location: header and a 3XX response code), this option will make curl redo the request on the new place.

**Comment by darknet1944** [comment]
@vchrizz - Thank you! your instructions worked!

**Comment by darknet1944** [comment]
Using command line provided by vchrizz I was able to install wireguard. Thank you. Issue is closed.
