### ISSUE TITLE
"Description" item for peers.

### ISSUE THREAD

**Issue by gsloop** [WireGuard/wireguard-vyatta-ubnt#150]
Example: set interfaces wireguard wg0 peer abcde= description "Jimmy Peer"

This makes keeping track of which "peer" is which way WAY easier, since you don't have to go hunt down public keys and do a comparison.

**Comment by dc361** [comment]
The description field does exist for the edgerouter at the moment.   To add a description you can use the following syntax

```
configure
set interfaces wireguard wg0 peer +abcde= description 'Mike Tab2021'
commit
save; exit

```

**Comment by gsloop** [comment]
I thought I tried that, without luck - but perhaps I had a typo somewhere.
I'll try again!

Thanks!
