### ISSUE TITLE
Fail to install on UGW3 - 4.4.57.5578372

### ISSUE THREAD

**Issue by Looooopy** [WireGuard/wireguard-vyatta-ubnt#152]
### Package version

1.0.20220627

### Firmware version

4.4.57.5578372

### Device

UniFi Security Gateway - UGW3

### Issue description

Trying to install after having it before flashing the new firmware, but now when i try to install it by running `sudo ./setup_wireguard.sh` i get this output:

```
FATAL: Module udp_tunnel not found.
FATAL: Module ip6_udp_tunnel not found.
loading wireguard...
Unsupported Kernel version 3.10.107-UBNT
```

**Comment by catap** [comment]
I just installed via dpkg packages with instruction from https://github.com/WireGuard/wireguard-vyatta-ubnt/wiki/EdgeOS-and-Unifi-Gateway

Remarks:
1. I've used `openssl rand -base64 32` on my laptop to create keys;
2. I've used `wg pubkey` to get public key from created private key;
3. Inside `config.gateway.json` I've put desired server private key inside `"private-key"`, not a file;
4. I've switched to legacy UI to be able force provisioning UGW to get updated `config.gateway.json`.

I've used:
```
ubnt@gw:~$ cat /etc/version
UniFiSecurityGateway.ER-e120.v4.4.57.5578372.230112.0823
ubnt@gw:~$ 
```
