### ISSUE TITLE
PersistentKeepAlive on wg interface

### ISSUE THREAD

**Issue by GogoFC** [WireGuard/wireguard-vyatta-ubnt#155]
Hello

I setup EdgeRouter X v2.0.9 as a Wireguard client. It's peer is a VPS. The purpose is to be able to SSH into it. 

I can SSH into it but after a while I can't anymore until I ping the VPN server from the Router. For now I can ping the server every 25 seconds so that the tunnel keeps alive but it would be nice to be able to include this for the Routers behind NAT.

I tried this, I thought it was gonna work :)

`set interfaces wireguard wg23 peer $PUBLICKEY persistentkeepalive 25`

Also it would be nice to be able to name the interface something other than wg0-999 like a name of the site or office. Could be useful for site-to-site to name the interface by the site name or location. 

*Edit:
Well I just read that comment, from Jan 5th, that EdgeOS v 3 has their own Wireguard package and so my Feature Request is pointless.

In any case thanks a lot for this. I can't get my Dell  Precision Powerstation to `poweroff` while Daliy Power On is enabled so I'm gonna have to `wakeonlan` from Router. 

My Edge will not upgrade to V3 so I won't be testing that anytime soon, I do wonder if it's good thought.

**Comment by boteman** [comment]
You will still need a proper configuration, though. Try
persistent-keepalive 25
with a hyphen.

**Comment by GogoFC** [comment]
oh wow thanks it worked. I had crontab ping server every minute. That actually also worked but now I can remove that.
