### ISSUE TITLE
wireguard-tools update

### ISSUE THREAD

**Issue by phillipmcmahon** [WireGuard/wireguard-vyatta-ubnt#17]
Not really an issue, wanted to know whether wireguard-tool updates will also be included in this package.

**Comment by FossoresLP** [comment]
Hi, I'll release a new version with the updated WireGuard tools soon. The commit should be in later today and a release will probably be added tomorrow (after CI completes successfully).

**Comment by FossoresLP** [comment]
Release is out, closing
