### ISSUE TITLE
Install failure on USG3

### ISSUE THREAD

**Issue by rojaxthegreat** [WireGuard/wireguard-vyatta-ubnt#19]
When I try to install this on my USG3 it gives this error: `dpkg-deb: error: 'ugw3-v1-v1.0.20200506-v1.0.20200510.deb' is not a debian format archive
`
USG version 4.4.51.5287926

**Comment by nagubal** [comment]
Works fine for me.
How did you download the file ?
`curl -sL https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20200506-2/ugw3-v1-v1.0.20200506-v1.0.20200510.deb -o ugw3-v1-v1.0.20200506-v1.0.20200510.deb`

Check the .deb file size after downloading

**Comment by rojaxthegreat** [comment]
I had tried downloading it twice on friday and had the same problem, but today it worked fine, just bad download I guess.  Thanks
