### ISSUE TITLE
non-stop PTR requests

### ISSUE THREAD

**Issue by mxmartins** [WireGuard/wireguard-vyatta-ubnt#22]
I have an ER8-XG on firmware 2.0.9 beta3.  Wireguard on version e1000-v2-v1.0.20200506-v1.0.20200319 runs just fine.

After I upgraded to Wireguard e1000-v2-v1.0.20200506-v1.0.20200510, I run into a problem where the ER8-XG is in a non-stop loop sending PTR requests to my DNS (internal pihole).

After upgrading the ER8-XG, the router and the DNS (pihole) work just fine.  But as soon as a Wireguard client connects to the network, the ER8-XG sends PTR requests to my DNS (pihole) asking for 3.0.10.10.in-addr.arpa.  I'm seeing over 1000 PTR requests per minute, and it's crushing the DNS server....  The 10.10.0.3 is the address for the device on the Wireguard network.

I downgraded to the previous version of the Wireguard (e1000-v2-v1.0.20200506-v1.0.20200319) and the problem goes away.  

I tried again by upgrading to the newer Wireguard version, and the PTR problem comes right back.

Can you please take a look at it and see what the problem is?

**Comment by mxmartins** [comment]
An update.... under the previous wireguard version, the problem is still there....  So, it could be an issue with the Router Firmware....  Pursuing that avenue as well....

**Comment by mxmartins** [comment]
It turns out that Conditional Forwarding settings in PiHole were causing a DNS loop.... I'm still trying to track down exactly how that was taking place, but issue appears to be resolved....

**Comment by FossoresLP** [comment]
@mxmartins Are you still considering this a potential issue with this package? Otherwise please close the issue.
