### ISSUE TITLE
Provide an easy upgrade command

### ISSUE THREAD

**Issue by evil-dog** [WireGuard/wireguard-vyatta-ubnt#28]
This is a feature request.

It would be nice if wireguard could provide an easy upgrade command. Something similar to how the Edgerouter is upgraded. You run the "add system image" command with a file or URL to the new version. This automatically downloads and applies the new system image to the router.

For wireguard it would be nice if there were a command like "update wireguard package". By default this command could reach out to github to find the latest version and confirm with the user if they want to upgrade. It should also allow specifying a version, URL, and/or file to allow rollbacks to older versions if there are issues with the latest one.

This mechanism should preserve the current wireguard config and if possible update the wireguard modules without needing to reboot the router.

**Comment by stoffeastrom** [comment]
@evil-dog 

I've been using a modified version of this [script](https://github.com/whiskerz007/ubnt_get_wireguard). Looks like it's updated to point at this repo instead so should just work. Has been working without any problems for me at least with ER-Lite 3 and v2 firmware

**Comment by FossoresLP** [comment]
@evil-dog Your best bet for now will be to use a script like the one suggested above but please do so at your own discretion.
Updates do not receive much testing right now so I am not comfortable with providing any built in solution to upgrade since this could cause a lot of complications when an update ever has issues.

**Comment by vchrizz** [comment]
@evil-dog I was looking for a similar feature, see issue #105.
Check out [ER-wizard-WireGuard](https://github.com/vchrizz/ER-wizard-WireGuard), maybe this also solves your feature request?

**Comment by FossoresLP** [comment]
I'll close this as not planned and recommend using either the script by whiskerz007 or the wizard by vchrizz.
