### ISSUE TITLE
Will this release use multiple processors? Now or ever?

### ISSUE THREAD

**Issue by farmwald** [WireGuard/wireguard-vyatta-ubnt#3]
If I remember correctly, the previous lochnair-vyatta was single threaded.
On a single CPU with the Edgerouter 8 (Infiniity), I get about 60 MB/sec wireguard thruput.
That's fine, but more is always better.

**Comment by zx2c4** [comment]
WireGuard should be multithreaded by default. Can you provide some technical findings on why you suspect this is single threaded?

**Comment by farmwald** [comment]
From the comment:
"@neilalexander  WireGuard is meant to be multithreaded; Ubiquiti just lacks the option for it in their kernel. "
on page https://community.ui.com/questions/Release-WireGuard-for-EdgeRouter/3765d2a4-1952-4629-948a-3ac9d9c22311.
Also when I use a EdgeRouter 8 (16 cpus x 1800MHz), I get 60MB/s which seems right for a single processor and low for many processors.

**Comment by farmwald** [comment]
Sorry, I accidentally close this.

**Comment by zx2c4** [comment]
We haven't required `CONFIG_PADATA` in an incredibly long time. When @FossoresLP releases the new debs tomorrow, try updating and seeing if you're in better shape.

**Comment by zx2c4** [comment]
@farmwald So, do you find this repo produces faster modules for you?
