### ISSUE TITLE
Documentation update link

### ISSUE THREAD

**Issue by Amoeba00** [WireGuard/wireguard-vyatta-ubnt#36]
In the [binaries](https://github.com/WireGuard/wireguard-vyatta-ubnt#binaries) section, happened to notice that the url for [musl libc](https://www.musl-libc.org/) is now in the process of migrating to its new home [here](https://musl.libc.org/).

**Comment by FossoresLP** [comment]
Thanks for the notice, I will update that link soon. Leaving this open until then.
