### ISSUE TITLE
Connecting to remote WireGuard server

### ISSUE THREAD

**Issue by jrote1** [WireGuard/wireguard-vyatta-ubnt#39]
Is it possible to connect a remote WireGuard server? I want to do this as my IP is dynamic and I want to route traffic through a static IP using WireGuard.

Thanks in advance

**Comment by FossoresLP** [comment]
Hi, connecting to a remote server is possible. This is the same WireGuard that is available on all other Linux platforms, just built for EdgeOS.
Please see [README#Usage](https://github.com/WireGuard/wireguard-vyatta-ubnt#usage) for an example. You need to configure the remote server as a normal peer just like you would on any other platform.
Further questions regarding configuration should not be reported as issues here but could instead be posted i.e. in the [Ubiquiti Forums thread for WireGuard](https://community.ui.com/questions/Release-WireGuard-for-EdgeRouter/3765d2a4-1952-4629-948a-3ac9d9c22311).

**Comment by jrote1** [comment]
I managed to figure out thank you, sorry am new to WireGuard was just me being dumb
