### ISSUE TITLE
Tag out of sync with repo version

### ISSUE THREAD

**Issue by zx2c4** [WireGuard/wireguard-vyatta-ubnt#4]
The 20200429 tag appears to have 20200426 in the ci file:

https://github.com/WireGuard/wireguard-vyatta-ubnt/blob/1.0.20200429-1/.gitlab-ci.yml#L15

This causes wireguard.com/install/ to show out of date info as well.

**Comment by FossoresLP** [comment]
The tag has been fixed.
I will try to manually tag releases to prevent this from happening in the future.
