### ISSUE TITLE
install error on UWG

### ISSUE THREAD

**Issue by merkleID** [WireGuard/wireguard-vyatta-ubnt#45]
Hi,
trying to install on a USG3, so I did:

ubnt@USG:/$ sudo curl https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20200729-1/ugw3-v1-v1.0.20200729-v1.0.20200513.deb --output ugw3-v1-v1.0.20200729-v1.0.20200513.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0   1485      0 --:--:-- --:--:-- --:--:--  1630
ubnt@USG:/$ sudo dpkg -i ugw3-v1-v1.0.20200729-v1.0.20200513.deb
dpkg-deb: error: `ugw3-v1-v1.0.20200729-v1.0.20200513.deb' is not a debian format archive
dpkg: error processing ugw3-v1-v1.0.20200729-v1.0.20200513.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 ugw3-v1-v1.0.20200729-v1.0.20200513.deb

In doubt, I tried also with the ugw4 version, but no luck again:

ubnt@USG:/$ sudo dpkg -i ugw4-v1-v1.0.20200729-v1.0.20200513.deb
dpkg-deb: error: `ugw4-v1-v1.0.20200729-v1.0.20200513.deb' is not a debian format archive
dpkg: error processing ugw4-v1-v1.0.20200729-v1.0.20200513.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2

Where I am wrong?

Thank-you

**Comment by FossoresLP** [comment]
GitHub does not provide a direct link to the package file. You will have to tell curl to follow redirects (```curl -L```).

**Comment by merkleID** [comment]
you are perfectly right.
thank-you.

**Comment by merkleID** [comment]
> GitHub does not provide a direct link to the package file. You will have to tell curl to follow redirects (`curl -L`).

you are perfectly right.
thank-you.
