### ISSUE TITLE
USG site to Site

### ISSUE THREAD

**Issue by maletazul** [WireGuard/wireguard-vyatta-ubnt#49]
Hi Team,

anyone try a USG - USG site to site with wireguard?

**Comment by FossoresLP** [comment]
Hi @maletazul,

the GitHub issues are not really meant for user support.
You will most likely be better served by posting in the [UI forums thread](https://community.ui.com/questions/Release-WireGuard-for-EdgeRouter/3765d2a4-1952-4629-948a-3ac9d9c22311).
