### ISSUE TITLE
No wg0 interface after installing

### ISSUE THREAD

**Issue by ShawnDordeJay** [WireGuard/wireguard-vyatta-ubnt#50]
Hi, I have no interface wg0 after installing wireguard on my USG3. I installed the newest release and updated all my components. Already tried to uninstall, reboot and install again but still no interface wg0 available. Does somebody have a clue, what is wrong here? Thanks in advance

**Comment by dc361** [comment]
The interface doesn't show up until you have it configured (on the Edgerouter - not sure on the USG, perhaps someone with one could chime in...)

**Comment by ShawnDordeJay** [comment]
do you mean, until I created the config.gateway.json on the controller and provisioned to the USG3?

**Comment by dc361** [comment]
Correct as far as I know...

**Comment by ShawnDordeJay** [comment]
still no interface, even after creating config.gateway.json and provisioning to USG3. Any other idea?

**Comment by ShawnDordeJay** [comment]
My config.gateway.json was invalid (checked my json file with some online tool; comments from the example are not allowed) and was located at the wrong place. The right location is (Raspberry Pi) `/usr/lib/unifi/data/sites/<site-id>` and not as I tought `/var/lib/unifi/data/sites/<site-id>`. After correcting those things, I got an error that the subnet in my json file already exists. So i had to delete the subnet on my controller, provision again and it worked.
