### ISSUE TITLE
Bug/Edegerouter X DNS not able to be defined in the CLI for WG interface.

### ISSUE THREAD

**Issue by Ssezra** [WireGuard/wireguard-vyatta-ubnt#52]
Edegerouter X e50v2.deb latest. The command line doesn't seem to give an option to set a DNS = statement on the wireguard interface. DNS can be set via edgeos dhcp-server or local nameserver but the WG interface itself can't set dns via the cli. (As other implementations of wireguard can) Clients behind the VPN are unable to resolve dns names. ( For example, an xbox on a subnet whose traffic is being forwarded via modified table through the WG interface to an endpoint providing a masquerade) Also I don't see a way to refer to a config file and can only hardset configuration via edgeos WG interface. Is there another way to resolve dns for clients going through wireguard?

**Comment by Ssezra** [comment]
Disregard on the dns resolving. Found an oversight. Though I do still wonder about not being able to set DNS under the interface like the other wireguard implementations.

**Comment by razor950** [comment]
I have a working site to site setup and I'd like to specify the DNS which would be configured as Site A uses Site B's DNS for all Site B endpoints and viceversa; Site B uses Site A's DNS for all its endpoints but given that the interfaces don't allow for specifying a DNS, I am unsure how to handle this. 

Could this be revisited or explained if its already possible to configure.
