### ISSUE TITLE
Latest release (1.0.20201112) fails to install on E50 v1

### ISSUE THREAD

**Issue by dskorzewski** [WireGuard/wireguard-vyatta-ubnt#56]
I've downloaded package for Edgerouter X (E50) v1 and got following error when trying to install it:
`$ sudo dpkg -i /tmp/e50-v1-v1.0.20201112-v1.0.20200827.deb
(Reading database ... 35424 files and directories currently installed.)
Preparing to replace wireguard 1.0.20200908-1 (using .../e50-v1-v1.0.20201112-v1.0.20200827.deb) ...
This package contains the wireguard kernel modules for , you're trying to install it on 3.10.107-UBNT. Aborting.
dpkg: error processing /tmp/e50-v1-v1.0.20201112-v1.0.20200827.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /tmp/e50-v1-v1.0.20201112-v1.0.20200827.deb`
I've got EdgeOS v1.10.11

**Comment by MichaelVasilyev** [comment]
Same for me (e300 v2)

Dawid Skórzewski <notifications@github.com> 14 ноября 2020 г. 19:28:36 написал:

**Comment by FossoresLP** [comment]
Thanks for reporting this. I will look into it ASAP.

This is what happens when I do not put in the time to test releases.

A new release should be ready in a few hours.

**Comment by timkgh** [comment]
Same on E300 v2 (ER-12) running v2.0.9 (which is not officially released yet but very close):
`This package contains the wireguard kernel modules for , you're trying to install it on 4.9.79-UBNT. Aborting.`

**Comment by FossoresLP** [comment]
The issue was a wrong path in the CI that messed up the embedding the kernel version in the install script.
A fix should be ready in a few minutes.
If someone here wants to test the build (I do not have an ER available right now) let me know.

**Comment by FossoresLP** [comment]
Fix is out now. Please check if the new release works.

**Comment by timkgh** [comment]
Still broken, `/usr/bin/wg` is not executable :(

**Comment by FossoresLP** [comment]
Really sorry for that - I hope the next release finally fixes everything.

ETA ~10min

**Comment by FossoresLP** [comment]
The new release is out (marked as a pre-release this time). Hoping this finally works.

**Comment by timkgh** [comment]
Thank you! Seems to work now on v2.0.9 if you want to update the release page to list this version in addition to v2.0.8-hotfix.1

**Comment by FossoresLP** [comment]
@timkgh Thanks for letting me know. The versions on the release page are the ones whose source was used in the build process. I will update that when 2.0.9 is actually released.

When no more issues are reported in the next few hours I will remove the pre-release tag.

**Comment by dskorzewski** [comment]
Seems to be working with the latest pre-release.
I think the issue can be closed

**Comment by FossoresLP** [comment]
Thanks for reporting back.
Closing.
