### ISSUE TITLE
Version 20201112-3 seems to identifiy as 20201112-1.

### ISSUE THREAD

**Issue by BrianG61UK** [WireGuard/wireguard-vyatta-ubnt#57]
I tried 20201112-3 on my Edgerouter X with EdgeOS 2.0.9. It works fine but when I do:

show version all

it says I have version 20201112-1.

I guess that's only a minor problem and only if using @whiskerz007's script to auto update at intervals.

**Comment by FossoresLP** [comment]
You are right, I totally forgot to upgrade the package release when fixing the release issues.

I'm not quite sure whether to do another release today (and continue the spam from yesterday) or wait for some more changes.

**Comment by BrianG61UK** [comment]
For myself I don't mind which you do now that I know the situation.

**Comment by FossoresLP** [comment]
New release with correct version number is out now.

**Comment by BrianG61UK** [comment]
Excellent, thanks.
