### ISSUE TITLE
EdgeOS Firmware v2.0.9 is available

### ISSUE THREAD

**Issue by TXC** [WireGuard/wireguard-vyatta-ubnt#59]
https://community.ui.com/releases/EdgeMAX-EdgeRouter-Firmware-v2-0-9-v2-0-9/d75f346d-d734-4026-97a8-7b2d5cc4e079

**Comment by FossoresLP** [comment]
Sadly Ubiquiti does not seem to have their GPL archives readily available anymore.
I will try to get in touch but until they release the necessary kernel source there will not be a new release of this package.

**Comment by naggie** [comment]
The kernel reports as `Linux ubnt 4.9.79-UBNT #1` in both the new version and the previous version. I tried `e300-v2-v1.0.20201112-v1.0.20200827.deb` and it appears to work on my Edgerouter 4 -- **but beware** it seems necessary to restore the config you had set before the upgrade, after the dpkg installation --  else you'll lose your wireguard interfaces. (I can't remember if the docs say that anyway :) )

**Comment by masezou** [comment]
I tried to upgrade from Edgerouter 4 with v2.0.8-hotfix.1 to v 2.0.9.
Once I have upgraded v 2.0.9 firmware, All Wiregurad configuration was restored and worked fine.

**Comment by nzapponi** [comment]
> The kernel reports as `Linux ubnt 4.9.79-UBNT #1` in both the new version and the previous version. I tried `e300-v2-v1.0.20201112-v1.0.20200827.deb` and it appears to work on my Edgerouter 4 -- **but beware** it seems necessary to restore the config you had set before the upgrade, after the dpkg installation -- else you'll lose your wireguard interfaces. (I can't remember if the docs say that anyway :) )

I had the same issue on my EdgeRouter X: all the interface configuration was lost following the upgrade!
First time it happens on an upgrade, weird.

**Comment by masezou** [comment]
I have checked why my setup was successful.
# ls /config/data/firstboot/install-packages/
bmon_4.0-1_mips.deb                          libconfuse-common_3.0+dfsg-2+deb9u1_all.deb
e300-v2-v1.0.20201112-v1.0.20200827.deb      libconfuse1_3.0+dfsg-2+deb9u1_mips.deb

# less /var/log/ubnt-firstboot-pkg-install.log

Preparing to unpack .../e300-v2-v1.0.20201112-v1.0.20200827.deb ...
Adding 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to /opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'
Adding 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta by wireguard'
Adding 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def.vyatta by wireguard'
Unpacking wireguard (1.0.20201112-1) ...

I usually put deb file in /config/data/firstboot/install-packages/. It seemed the deb files in /config/data/firstboot/install-packages/ were installed after install new firmware.
I believe e300-v2-v1.0.20201112-v1.0.20200827.deb or v1 file was in /config/data/firstboot/install-packages/, it would be fine.

**Comment by nzapponi** [comment]
The problem for me wasn't the wireguard package - that's was re-installed correctly after upgrading - but the interface config that was lost.

**Comment by FossoresLP** [comment]
It's interesting this is happening only with the latest firmware upgrade.
There have been no changes to this package besides the CI pipeline doing the packaging.
@nzapponi Which version were you using? 1.0.20201112 or an older version?

**Comment by nzapponi** [comment]
I was using an older version, but the fact that the interface config was gone makes me think it was something that changes on the OS side rather than on this package?

**Comment by FossoresLP** [comment]
Yes, I think it is something on the OS side, too.
I just wanted to validate whether it could have something to do with the packaging changes. If you were using an older version this is not possible because 1.0.20201112 was the first version built using the new pipeline.
This should definitely be noted in the README. I'll try to add it soon but feel free to open a PR.

**Comment by FossoresLP** [comment]
New release is now build for v2.0.9.
