### ISSUE TITLE
[Feature/Support REQ]

### ISSUE THREAD

**Issue by rebelgtp** [WireGuard/wireguard-vyatta-ubnt#67]
This is not really an issue but more like a request for investigation towards integrating support to another project given the lack of GUI support from UBNT in the UI currently.

This request relates to the following project (https://github.com/EmbarkStudios/wg-ui?ref=madewithsvelte.com) and seems to be a suitable surrogate for creating a frontend for easy creation of Peer entries with the Vyatta instances of Wireguard.

I envision Wireguard UI maybe running on the Unifi Controller and can edit the json file for USG devices or Wireguard UI running within the Vyatta Wireguard package directly on EdgeOS devices.

Perhaps some collaboration with developers of the other project can be performed to somehow pull Wireguard UI into the ubnt builds?

**Comment by FossoresLP** [comment]
Thank you for the suggestion. There are however multiple issues I have with this:
- the configuration through wg-ui would be out of sync with the vyatta configuration
- a router is critical infrastructure so nothing that is not really needed should be run on them
- wg-ui is larger than this package by an order of magnitude
- I have some security concerns about wg-ui, e.g. they are generating private keys for the clients on the server and transferring them over the network

My suggestion would therefore be to either
- create a separate package for wg-ui which could work together with this one, or
- modify wg-ui in a way that it can run on a different device and configure WireGuard on the USG/ER via SSH
