### ISSUE TITLE
Download Folder named 1.0.20210219-2 but internal program named 1.0.20210219-1 still

### ISSUE THREAD

**Issue by mxmartins** [WireGuard/wireguard-vyatta-ubnt#68]
Any particular reason why the download folder for this most recent update includes the version number of 1.0.20210219-2 but the internal program version still reflects the previous version?

I'm running an automatic update script and this causes the update to install the same version every day since the version numbers never match.

Any chance the version number can be matched in both locations?

**Comment by FossoresLP** [comment]
Hi, thanks for reporting. This was an oversight on my part. I forgot to update the package release internally.
There was a new release so the 2 is correct.
If this is a serious issue for you, I can push a -3 release with a corrected internal release number.

**Comment by mxmartins** [comment]
It was not a serious issue, but I wanted to bring it to your attention.  I also wanted to understand the reasons behind it to determine if the script logic needed to be changed..

 

I see you just pushed the fix.  Thank you very much!
