### ISSUE TITLE
Defining fwmark breaks wireguard config

### ISSUE THREAD

**Issue by mvn23** [WireGuard/wireguard-vyatta-ubnt#77]
Since my weekly auto-update this morning, I noticed wireguard was not working anymore on my ER4 v1.10.11.
When checking the web interface, there were no wireguard interfaces present and the wireguard branch in the config tree was empty.
The related parts were still present in config.boot, so I tried a reboot without success.
I made a backup of my config.boot and decided to try and recreate the wireguard config. All went fine until I wanted to commit the changes. The UI complained about `No such device` when setting the fwmark. I restored my backup of config.boot and removed the fwmark lines from the config. Now after a reboot everything is fine again, but when I set the fwmark option again it only works until the next reboot.

Steps to reproduce:
* Add a new wireguard interface
* Set a private key and `fwmark`
* Commit and Save

**Comment by FossoresLP** [comment]
@whiskerz007 Could this be an issue with the commit order with the new scripts?
It seems like fwmark is applied before the interface is created, causing an error.

**Comment by whiskerz007** [comment]
@FossoresLP `fwmark` does not have a priority set. Would you like me to create a PR, or do you want to handle it?

**Comment by whiskerz007** [comment]
Setting `fwmark` priority to `460` seems to resolve the problem.

**Comment by FossoresLP** [comment]
Would be great if you could open a PR. Thanks a lot for figuring all these issues out.
