### ISSUE TITLE
Package Error still (with pakage from new build)

### ISSUE THREAD

**Issue by dc361** [WireGuard/wireguard-vyatta-ubnt#8]
Package download link:   https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20200429-2/e50-v1-v1.0.20200429-v1.0.20200319.deb

Error on install:   ```
sudo dpkg -i e50-v1-v1.0.20200429-v1.0.20200319.deb
dpkg: warning: parsing file '/var/lib/dpkg/available' near line 1552 package 'wireguard':
 'PACKAGE_ARCH' is not a valid architecture name: character `_' not allowed (only letters, digits and characters `-')
(Reading database ... 35424 files and directories currently installed.)
Preparing to replace wireguard 1.0.20200429-1 (using e50-v1-v1.0.20200429-v1.0.20200319.deb) ...
Unpacking replacement wireguard ...
Setting up wireguard (1.0.20200429-1) ...

```

**Comment by zx2c4** [comment]
Are you sure you installed the right one? Or maybe that error is from removing the prior one?

```
zx2c4@thinkpad ~/Downloads/Chrome $ ls
e50-v1-v1.0.20200429-v1.0.20200319.deb
zx2c4@thinkpad ~/Downloads/Chrome $ ar x e50-v1-v1.0.20200429-v1.0.20200319.deb 
zx2c4@thinkpad ~/Downloads/Chrome $ ls
control.tar.gz  data.tar.gz  debian-binary  e50-v1-v1.0.20200429-v1.0.20200319.deb
zx2c4@thinkpad ~/Downloads/Chrome $ tar xf control.tar.gz 
zx2c4@thinkpad ~/Downloads/Chrome $ rg PACKAGE_ARCH
zx2c4@thinkpad ~/Downloads/Chrome $ rg Architecture
control
4:Architecture: mipsel
```

**Comment by dc361** [comment]
Perhaps -- it does seem to work ok I'll try to re-install over the top and see if it throws the same error.

Ok.. so it worked fine:

```
ubnt@ub-test:/config/wireguard$ configure
ubnt@ub-test# set interfaces wireguard wg0 route-allowed-ips false
ubnt@ub-test# commit
ubnt@ub-test# delete interfaces wireguard
ubnt@ub-test# commit
ubnt@ub-test# sudo rmmod wireguard
ubnt@ub-test# sudo dpkg -i e50-v1-v1.0.20200429-v1.0.20200319.deb
(Reading database ... 35424 files and directories currently installed.)
Preparing to replace wireguard 1.0.20200429-1 (using e50-v1-v1.0.20200429-v1.0.20200319.deb) ...
Unpacking replacement wireguard ...
Setting up wireguard (1.0.20200429-1) ...
ubnt@ub-test# sudo modprobe wireguard
ubnt@ub-test# load
Loading configuration from '/config/config.boot'...
Load complete.  Use 'commit' to make changes active.
ubnt@ub-test# commit
```
