### ISSUE TITLE
Upgrade fails at commit step with "ip source-validation strict" set on tunnel

### ISSUE THREAD

**Issue by poisonsnak** [WireGuard/wireguard-vyatta-ubnt#81]
I just upgraded from 1.0.20210124-1 to 1.0.20210219-4, I think this is my first upgrade with the template rewrite.  Everything in the upgrade went fine until I tried to commit the config back in:

```
root@router# commit
[ interfaces wireguard wg1 ip source-validation strict ]
sh: /proc/sys/net/ipv4/conf/wg1/rp_filter: No such file or directory

[ interfaces wireguard wg3 ip source-validation strict ]
sh: /proc/sys/net/ipv4/conf/wg3/rp_filter: No such file or directory

[ interfaces wireguard wg5 ip source-validation strict ]
sh: /proc/sys/net/ipv4/conf/wg5/rp_filter: No such file or directory

[ interfaces wireguard wg0 ip source-validation strict ]
sh: /proc/sys/net/ipv4/conf/wg0/rp_filter: No such file or directory

[ interfaces wireguard wg2 ip source-validation strict ]
sh: /proc/sys/net/ipv4/conf/wg2/rp_filter: No such file or directory

[ interfaces wireguard wg4 ip source-validation strict ]
sh: /proc/sys/net/ipv4/conf/wg4/rp_filter: No such file or directory

Commit failed
```

I tried issuing commit again with the same result.  I then removed the problem part of the config (`delete interfaces wireguard wg1 ip source-validation strict` , etc.) and tried to commit again and got

```
root@router# commit
Commit failed
```

, but I tried it again and it went through the second time.  Then I added `ip source-validation strict` back in for the tunnels and committed and that went fine.  I compared the running configuration to my latest backup and they're identical, so I didn't lose anything.

**Comment by FossoresLP** [comment]
@whiskerz007 This looks like another issue with the order of operations to me. Would changing the priority to 460 (or the number you mentioned in the other issue, I can't remember right now) fix this, too?
