### ISSUE TITLE
wireguard-vyatta-ubnt preshared-key

### ISSUE THREAD

**Issue by RealMuhko** [WireGuard/wireguard-vyatta-ubnt#85]
Hello.

EdgeRouter X v2
wireguard-vyatta-ubnt version: e50-v2-v1.0.20210219-v1.0.20210315.deb

I am wondering if the wireguard-vyatta-ubnt application does not support preshared-key function ?

I can set the private-key with "set interfaces wireguard wg0 private-key <PRIVATE KEY>"

But I can not set the preshared-key with "set interfaces wireguard wg0 preshared-key <PRESHARED KEY>"

Thanks in advance!

Best Regards From

Martin Brandt.

**Comment by dc361** [comment]
HI @RealMuhko 

The preshared-key attribute goes with the peer definition so you can have a unique preshared key for each peer.  The Edgerouter syntax would be as follows:

`set interfaces wireguard wg0 peer zaaaaabbbcccwwwhateverw4Yido3ueQasdfaso= preshared-key 44character32bytebase64key
`

**Comment by boteman** [comment]
Can this ticket be closed?
