### ISSUE TITLE
Edgerouter X SFP e50 Release?

### ISSUE THREAD

**Issue by pr0j3ctx** [WireGuard/wireguard-vyatta-ubnt#96]
Hi,

should the e50 release be used for the edgerouter X SFP as well as for the edgerouter X?

If so, could you add that to the list?

Greets,
pr0

**Comment by dulitz** [comment]
I can't add it to the list, but the answer is yes it should.

**Comment by pr0j3ctx** [comment]
OK, thank you for the information.
I'll leave the issue open so that the information can be documented in the release notes.

**Comment by pr0j3ctx** [comment]
Ok, thanks for information. 
I opened a pull request where I added the device. #97

**Comment by FossoresLP** [comment]
Thanks for the PR, it has been merged. All future releases will include the ER-X SFP in the list.
